### ISSUE TITLE
想不出实际应用？

### ISSUE THREAD

**Issue by forliuyifei** [MoonBegonia/hexo-tag-remote-code#1]
感觉意义不怎么大。
要是 hexo tag chart 插件能使用远程数据就好了。

**Comment by oevery** [comment]
这个插件就是为了在粘贴gist，repo 里的代码时不需要复制粘贴更新，只需要重新 build 一版就可以。局限就是不能直接加载远程数据，因为那时候考虑到网络的问题，不 build 静态的可能会有些地方访问不了所以就没做(gist 被墙了)。
hexo tag chart 没用过，不清楚。

**Comment by forliuyifei** [comment]
噢，原来是在 build 的静态时候直接拉取远程数据而不是在打开页面的时候让用户实时加载吗？ 
还是挺有用的。
